### ISSUE TITLE
Scroll to top, if click a link in the footer

### ISSUE THREAD

**Issue by KoljaL** [delay/sveltekit-auth-starter#14]
Yea, thats all.

And thanks for your work to create this collection 👍

**Comment by delay** [comment]
Interesting, I see if you scroll down on terms and then click privacy it does not render at the top of page.  This one may be difficult to figure out.  I will look into it.  Might be a bug in skeleton.dev, (how it handles app shell).  I believe someone mentioned app shell could be troublesome when using it.
