### ISSUE TITLE
Axiom Node is deprecated with replacement being Axiom JS

### ISSUE THREAD

**Issue by BradNut** [delay/sveltekit-auth-starter#19]
Axiom Node's site states: Deprecated, use [axiom-js](https://github.com/axiomhq/axiom-js) instead

My attempts to integrate `axiomhq/js` in place of the current implementation in this repository have not been successful. Errors as described in this [issue](https://github.com/axiomhq/axiom-js/issues/50) on their repository.

Any help to migrate this repository to `axiomhq/js` would be helpful for others trying to do the same.

**Comment by delay** [comment]
Thanks I will try and get this updated.  I will also accept a PR for this.

**Comment by delay** [comment]
fixed.
