### ISSUE TITLE
Missing template literal in email-messages.ts updateEmailAddressSuccessEmail

### ISSUE THREAD

**Issue by jannisrichter** [delay/sveltekit-auth-starter#4]
In line 52 a normal string is used instead of a template literal resulting in the email looking like this:

Your email address for ${APP_NAME} has changed.

**Comment by delay** [comment]
Good catch!  Thank you.  I put the wrong type of quotes around the string so it wasn't interpreting the variables around the string.  Thanks for very much for finding this.  It is fixed now!
