### ISSUE TITLE
use Nodemailer instead of aws-sdk/client-ses for Email Sending

### ISSUE THREAD

**Issue by ak4zh** [delay/sveltekit-auth-starter#9]
Nodemailer supports a wide range of email providers, including SMTP, Sendmail, and direct transport. So it can still leverage Amazon SES as an email service provider.

https://www.npmjs.com/package/nodemailer

**Comment by delay** [comment]
I will try and add this over the weekend.  I was trying to minimize packages but you are right it will give people more email options if they do not want to use SES.

**Comment by delay** [comment]
changed it to use nodemailer for mailing.

**Comment by KoljaL** [comment]
Cool, but can you update the readme 😇

**Comment by delay** [comment]
updated the readme... thanks...
